"""Explicit versions for persisted Trace cache payloads and semantics."""

INVESTIGATION_CACHE_SCHEMA_VERSION = 1
SNAPSHOT_CACHE_SCHEMA_VERSION = 1

INVESTIGATION_PROMPT_VERSION = 1
TOOL_SCHEMA_VERSION = 2
WORKSPACE_POLICY_VERSION = 2

